### ISSUE TITLE
Bug in Microsoft.Azure.EventGrid used in lab

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#174]
# Module: 10
#### Step: 00

Description of issue

There is a bug in the Microsoft.Azure.EventGrid package. The EventGridEvent Data property does not property handle an anonymous typed object. (A newer version of the library may fix this problem.)

**This fails:**  (see output below)
```
   var secondPerson = new     //anonymous type
   {
     FullName = "Alexandre Doyon",
     Address = "456 College Street, Bow, WA 98107"
   };
```

**This works:**
```
   var secondPerson = new  **Person**   // Person type
   {
     FullName = "Alexandre Doyon",
     Address = "456 College Street, Bow, WA 98107"
   };
```

**Of course you need a Person class:**   (add this after the final "}" in the class project.
```
  public class Person {
     public string FullName;
     public string Address;
  }
```

**Output in the eventviewer website:**
  before:  `"data": {},`
  after:     `"data": {` 
                   `"FullName": "Alexandre Doyon",`
                   `"Address": "456 College Street, Bow, WA 98107"`
                 `}`

**A discussion of the error.**
https://github.com/Azure/azure-sdk-for-net/issues/12244

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
This is related to #161

**Comment by seesharprun** [comment]
I updated the lab to use the latest NuGet package: [Azure.Messaging.EventGrid:4.1.0](https://www.nuget.org/packages/Azure.Messaging.EventGrid/4.1.0)

This caused a rewrite of the lab to use the new classes, but I think it makes the instructions a bit easier to follow.

The lab has been updated in #184 and we can close this issue.

**Comment by seesharprun** [comment]
![image](https://user-images.githubusercontent.com/5067401/113012984-48813700-9149-11eb-8a6f-b90c18fa35fe.png)

**Comment by microsmith** [comment]
Thanks for the fix! In hindsight, I liked the workaround I had a little better as we are creating honest C# object based on a type. Just felt better from a training point of view than an anonymous type. Both work, so all is good.

**Comment by seesharprun** [comment]
You are always welcome to fork the instructions, enable GitHub Pages and point your students there.

You can either recreate the fork each class, or merge changes down before each delivery. I know there’s a MCT who uses the latter strategy because the “blame” compare tool will tell them every change since the last delivery.

On the C# point, things can get very dicey. Do you lean functional, replace all members with lambdas, and use anonymous types whenever possible. Or, do you stay strictly object-oriented. I expect a huge debate here when the topic comes up of console applications vs. [top-level executables (scripts)]()
