### ISSUE TITLE
Instruction to open integrated terminal needs clarification

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#194]
# Module: all
## Lab: all

Description of issue
In almost all lab instructions is this instruction included when a terminal window in VSC has to be opened:
"In the Visual Studio Code window, right-click or activate the shortcut menu for the Explorer pane, and then select Open in Terminal."

This instruction cannot be fulfilled in the current VSC, at least I don't know what shortcut is meant here. Students are often asking about that. The instruction should be changed to something that is clear and will open a terminal in the correct folder, one solution could be:

"In the Explorer pane on the left hand site right-click Program.cs (or any other file) and click "Open in Integrated Terminal""

or

"From the menu bar click "Terminal" and select "New Terminal" to open an integrated terminal in the current folder."
![image](https://user-images.githubusercontent.com/37703728/114767054-77adc000-9d67-11eb-9920-7e1f6c34828d.png)

**Comment by seesharprun** [comment]
> To see the **Explorer** pane's shortcut menu, select **Explorer** on the left navigation menu and then right-click anywhere in the file explorer's pane. I think the text was recently changed to "Open in Integrated Terminal" to make way for tighter integration with the new Windows Terminal.

Updating the language used is a perfectly valid suggestion, but we have to be careful about the replacement text. It has to meet strict inclusivity requirements.

For example:
- We can't stay "click" because not all users will use a mouse
- We cannot use directions like up, left, right, or down as they are not inclusive of users with visual impairments
- We cannot say the right-click menu, so we got guidance that the right-click menu is officially called the "shortcut menu".

If other MCTs want to chime in, I can see a good argument for guiding users to the menu instead of the shortcut menu to keep things simple.
