### ISSUE TITLE
Following the instructions leads to 3rd party Vault

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#195]
# Module: 07
##### Step: 01

Description of issue
Following the instructions literally we end up deploying a third party Vault not Azure Key Vault.
Please don't let users search the Marketplace at all, instead they should always use the search bar in the portal which will search in different sources.

Repro steps:
1. In the Azure portal’s navigation pane, select the Create a resource link.
1. From the New blade, find the Search the Marketplace text box above the list of featured services.
1. In the search box, enter Vault, and then select Enter.

**Comment by seesharprun** [comment]
We include the Marketplace, by design, since all services are part of the Marketplace. This includes first-party services like Azure Key Vault.

In the past, we had trouble writing inclusive instructions for either the search bar or navigating through the "all services" link.

With that said, I think these instructions can be updated to ask the student to search for "Key Vault" instead of just "Vault". That step was completed in e608c12.

I will leave this open to see how other MCTs are navigating the portal.

**Comment by mkennten** [comment]
Works for me, too. Thanks! In other courses we are not using the Marketplace and it works okay, sure there will be changes from time to time, but as you see here with the Marketplace it's no difference. This is the second issue with something searched in the Marketplace already for this course, so I was wondering if this should be changed. But I'm fine with this solution, too.
