### ISSUE TITLE
Code to use Env. Variables or Key Vault instead of hard coding?

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#236]
Lab 06: 
Task 2: Modify the Program class
Step 4. Create a new Program class with two constant string properties named _clientId and _tenantId, and then create an asynchronous Main entry point method:
```
    private const string _clientId = "<app-reg-client-id>";
    private const string _tenantId = "<aad-tenant-id>";
```
Why not store strings in enviornment variables for use by this program so that it can be used without manual intervention by programmers? Also the class covered use of Key Vault in a previous lab.

**Comment by seesharprun** [comment]
In testing this lab using alternative workflows, the use of Key Vault and even managed identity obfuscated what MSAL was doing behind the scenes enough that it detracted from the value the students get from the lab. 

In this scenario, just spelling out that the MSAL library requires these two GUIDs makes it clear how everything works "under the hood." As a MCT, you can add value by delivering a demo where you use Key Vault for these secrets of skip them entirely in favor of managed identity.

There were some other considerations that led to keeping the lab simple within our constraints:

- The labs are task-focused with each lab focusing on a single task. Here it's just using MSAL for the first time (for many students)
- We cannot have dependencies between labs. We cannot assume that the students took a module before this on Key Vault because some deliveries may be piecemeal or out-of-order. If we add in all of the contextual explanations for Key Vault, this would explode the lab in length.
- Any code written by the students should be easily debugged and very plain and simple to read. We only require that they know C# and cannot assume they have advanced debugging skills. We also have to think about the complexity of troubleshooting problems with connection string values in a live lab setting.

As a trainer, I do think a demo of combining Key Vault and MSAL would be worth showing students.

**Comment by seesharprun** [comment]
In the spirit of keeping the labs easily debuggable and making sure each lab focuses on one overall task, this issue is being closed.
