### ISSUE TITLE
Lab 05 Do not use Cloud Shell

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#268]
# Module: 05
#### Step: 00

Description of issue
The cloud shell continues to fail sporadically and the content team has been asked to update the instructions to not use it

Also - as of mid July ACR build tasks are failing from cloudshell which are affecting many projects on github including this one.
Repro steps:

1.
1.
1.

**Comment by dqzhu** [comment]
For Lab 5 -- Exercise 2 -- Task 5 -- Step 3
az acr build --registry $acrName --image ipcheck:latest .

if you get error: 'NameType' object is not callable

This is because there is a  problem with azure-cli version on the default cloud shell v2.26.0. If you upgrade to v2.26.1, it will fix this problem.

Steps:

First run command in Cloudshell: pip install azure-cli
Then restart CLI

**Comment by dqzhu** [comment]
verify the version 

az --version

I am teaching AZ-204 now, we fixed the problem for all machines.

**Comment by thomash0815** [comment]
> pip install azure-cli

Hi, I did the upgrade, seemed to work in general, but I also get some errors, what does that exactly mean?

![Capture](https://user-images.githubusercontent.com/52786267/126606167-5908ef66-cd70-4732-8b55-7f2cf269db12.PNG)

**Comment by WigF1** [comment]
[This](https://stackoverflow.com/a/63280415) post seems to have more data about it. To confirm, you ran the command in the cloud shell, correct?

**Comment by JeffKoMS** [comment]
It looks like CLI version 2.27.0 has finally been released in the cloud shell. If you check your version and it's still 2.26.0 then just select the "restart cloud shell" option.

**Comment by JeffKoMS** [comment]
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.
