### ISSUE TITLE
Lab2 Swap E05 T03 and T04

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#447]
# Module: 02
#### Task: 03,04

Swap E05 T03 and T04
Reason: Visual Studio code shows Blob as missing reference. Students usually try to build it and they get error. It is confusing.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by WigF1** [comment]
@MOC-Labs-Review I don't know how you *can't* encounter the issue. As @bechynsky mentioned, despite telling them not to, students will habitually try a build once they have done Task 3. This is because the code as entered by them refers to a BlobAtribute that is not in scope. 

So they complete Exercise 5, Task 3, Step 13 and they will see an error because the BlobAtribute is not found. This same error will remain until they complete Task 4 and register the Azure Storage Blob extension.

A simple re-order of the two tasks will resolve any issues *AND* will be more akin to what they would actually do in real-life. You register dependencies *before* you start using their contents.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
