### ISSUE TITLE
Lab1 Screenshot should be updated -> optimize costs

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#488]
# Module: 01
#### Step: 00

Description of issue
![image](https://user-images.githubusercontent.com/64772417/168602182-4efec093-eb87-4e9a-9533-91d51a81ff6b.png)
now it defaults to Premium --> we could update and optimize azure costs
Repro steps:

1.
1.
1.

**Comment by msftnutta** [comment]
Thanks @unaihuete93 for reporting this issue. 

@JeffKoMS since we're now using CloudSlice, so there are two ways you may want to consider, 

first, retain the instruction but updating the screenshot by using a screenshot below as Premium tier will be selected by default

![image](https://user-images.githubusercontent.com/98095529/168830093-2876d4e0-65ea-49af-b22a-dcb49de05a3e.png)

or, second option, update the instructions to select the standard tier, use this following screenshot 

![image](https://user-images.githubusercontent.com/98095529/168830278-c9d5422b-869c-4c9c-a0fc-8f93a89ad11e.png)

**Comment by WigF1** [comment]
"As we're now using Cloud Slice" ??? Not every person attending the course will be using Cloud Slice labs, please don't modify lab steps solely on the basis of Cloud Slice usage. 

We need to address the outstanding PRs and Issues which are more critical than cost saving.

**Comment by unaihuete93** [comment]
Well cost saving is a side effect, not the important issue.

Specifying that **Standard S1** needs to be used, works for every user (cloudslice or not). **The screenshot needs to be updated at least.**
