### ISSUE TITLE
Suggested correction for AZ-204_02_lab.md

### ISSUE THREAD

**Issue by jngibert** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#68]
# Module: 02: Implement Azure Functions
#### Step: 02

Description of issue

RE: /Instructions/Labs/AZ-204_02_lab.md

In Lab "Exercise 4: Create a function that integrates with other services" on Task 3 ... Step 2 currently reads:
"From the App Service blade, locate and open the Integration pane for the GetSettingInfo function"

I believe it should read something like:
"Go to the Functions blade, select the GetSettingInfo function, and then select the Integration pane."

Repro steps:

1. Going to the App Service blade does not allow the student to access the Integrations pane for the GetSettingInfo function

**Comment by jngibert** [comment]
Okay. I looked at the Answer Key for this step in this lab and see that it has instructions that are very close to my suggestion.
This particular step stumped many people in my class today. We all missed the fact that were were *already* on the App Service blade for the GetSettingInfo function ... which led many of us to look for App Service on the available menus - and many clicked on App Service plan ... which doesn't take you anywhere close to where you need to go.

I'll review and see if a previous lab exercises in this module clearly identifies the "App Service" blade. The instructions as written are clear once you realize you are on the App Service blade and it is your starting point for this step.

**Comment by jngibert** [comment]
Module2(Lab 2), Exercise 4, Task 3, Step 2 is the first time that the phrase "App Service blade" is used in the lab manuals for this course.
At no point in the instructor slide deck, or instructor demos, is the "App Service blade" specifically identified.  The word 'blade' isn't use at all in the eManual for this course.
The term Blades were of course introduced and used in the Azure Fundamentals course ... but I've been using Azure for over a year and even I didn't catch on at first that I was already on the App Service blade in this step.

**Comment by seesharprun** [comment]
"Blades" is an interesting term because we don't know how else to describe the UI components that show up for each service.

- The AZ-204 certification exam and courseware assume that you have either taken AZ-900 or have equivalent knowledge, so it's understood that a student would be familiar with the Azure Portal terminology from that course
- We are in a strange situation where the "Functions" blade is gone. Functions are now developed within the "App Service" blade. That change happened at Build.

I'm definitely open to discussing how we can improve the language here.
