### ISSUE TITLE
Lab 01 : Many learner copy/paste SA key and NOT ConnectionString

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#776]
# Module/Lab: 00
#### Step: 00

Description of issue
Please add warning (or similar) so they include the connectinString and not the SA Key

Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by WigF1** [comment]
@unaihuete93 I'm currently working on a PR as this issue is a constant bane for MCTs. It stems from the days when the keys/constrs blade had a single 'Show' button like keyvaults still have. the instructions got changed very very slightly once each box had its own show button.

This is what I have for that step - does it look ok?

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/c9e7146d-30c7-46d0-b6c9-fa4d70e6b0bb)

**Comment by JeffKoMS** [comment]
Merging your PR with the fix later today.
