### ISSUE TITLE
Lab 6: localhost does not default to 5001 for some learners 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#779]
# Module/Lab: 00
#### Step: 00

Description of issue
I had many learners in my class were the given localhost address was not 5001, they randomly had different 5xxx addresses. 
Repro steps:

1.
1.
1.

### Relevant screenshots

**Comment by WigF1** [comment]
This is because the students changed the wrong settings in their lab..

They need to change the correct settings and it works as written. In the iisSettings section, they are instructed to change the sslPort. In the https profile, they are instructed to change the applicationUrl. 

![image](https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/assets/12164329/e71e3652-bf7c-4b4c-884e-306b6677fe3c)

This is not an issue with the labs as written. Consider closing the issue @unaihuete93

**Comment by unaihuete93** [comment]
Maybe worth adding the note or screenshot, half my learners did it wrong :(
