### ISSUE TITLE
AdventureWorks.bacpac file emtpy/ missing tables

### ISSUE THREAD

**Issue by PhilBroderick** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#9]
# Module: AZ-204
##### Step: 9

Description of issue
The AdventureWorks.bacpac file doesn't seem to have the required tables that are specified in the step: AdventureWorks.dbo.Models or AdventureWorks.dbo.Products

1. Follow steps to import AdventureWorks.bacpac file in Task 3
2. In task 4, run the query in Step 9, and you receive the following error:

![image](https://user-images.githubusercontent.com/33251762/76431738-f0df2480-63a9-11ea-83c2-956fc742a00b.png)

**Comment by seesharprun** [comment]
It is possible to connect to the new database before the import process has completed. You will receive a notification when the import is done. This occurs because the import process is two-fold:
1. First, the database is created
2. Second, the data and objects are imported from the .bacpac file

Here's how you can validate, go and look at your Tables list and expand the list. You should see two tables in the list like this:
![image](https://user-images.githubusercontent.com/5067401/76433998-799a9800-638b-11ea-9243-09197a12ad42.png)

**Comment by PhilBroderick** [comment]
Just noticed the process currently in progress!
![image](https://user-images.githubusercontent.com/33251762/76439048-baa6a280-63b3-11ea-9e45-ad9287f27871.png)
Taking quite a while, hopefully once that completes it should be sorted though - thanks!

**Comment by seesharprun** [comment]
No problem, it's not obvious that the import process takes awhile. In practice, it normally takes 10-15 minutes.

**Comment by thanhquangvo** [comment]
In my case, you need turn on "All Azure services and resources to access this server" in Firewalls and virtual networks. It turns off default.
https://docs.microsoft.com/en-us/azure/azure-sql/database/firewall-configure
