### ISSUE TITLE
Should we debug .NET applications in Visual Studio Code?

### ISSUE THREAD

**Issue by russgove** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#96]
# Module: 3
## Lab/Demo: 1

It would be really helpful if the lab explained how we can debug dotnet apps running in vscode. Stepping though the code lets devs understand what is happenning

**Comment by seesharprun** [comment]
Debugging is one of those things that eats so much time in a lab that we end up cutting content elsewhere. That's a big part of why we simply run the code in these labs.

One thing we could do is add a Note that says alternatively you can debug the code with a link to this page: <https://docs.microsoft.com/dotnet/core/tutorials/debugging-with-visual-studio-code>. We can inject the note after any time we have the student run ``dotnet run``. That gives the MCT freedom to recommend debugging while keeping the labs within the time constraints.

**Comment by russgove** [comment]
Thankyou! that would be helpful!

**Comment by russgove** [comment]
Also, in response to my previous issue, maybe we should just add a note with a link to the documentation about dotnet publish command. I'm sure it would be appreciated!

**Comment by russgove** [comment]
IMHO, I think the debugging should be part of the lab. People (at least me) learn so much more whwn they actually watch the code run and can examine the properties on the objects that are returned from the various calls to the azure apis.

**Comment by seesharprun** [comment]
This is a valid discussion to have. In the predecessor course (20532), we had labs with step-by-step instructions on how to debug. It led to a lot of support tickets/issues because of inexperience using the debugger on either the student or trainer behalf. It's just something that's difficult to write in a way that will pass test and not cause confusion. There's also an issue with the accessibility of the current debugger tooling (how do we make the debugger accessible to blind or color-blind developers?).

As a trainer, you can definitely add value to the classroom by having students walk step-by-step through the code in a debugger. I think that it works best if you do it as part of demos prior to the lab so students can use the debugger if they get stuck.

Looking to the future, [.NET 5](https://github.com/dotnet/roslyn) [.NET Interactive](https://github.com/dotnet/interactive) is going to reach a maturity level in November that will allow us to add projects that don't require as much overhead. We can write scripts without creating a project, manipulating extra files, or doing all the other stuff that eats up so much lab time. I think this will make it easier for students to debug the labs.

If nothing else, we can bring up debugging in train-the-trainer content and show MCTs how to use it to enhance the classroom experience. I like to think of each course as a baseline that is improved by each trainer's delivery.

**Comment by seesharprun** [comment]
While this issue is closed, we can still discuss the topic here. If an action item needs to be taken, we will reopen the issue.
